SELECT
  CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS `Nome completo`,
  JH.START_DATE AS `Data de início do cargo`,
  D.DEPARTMENT_NAME
FROM hr.employees AS E
INNER JOIN hr.job_history AS JH
  ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
INNER JOIN hr.departments AS D
  ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
ORDER BY 1 DESC;
