SELECT UCASE(concat(FIRST_NAME, ' ', LAST_NAME)) AS 'Nome completo',
START_DATE AS 'Data de início',
SALARY AS 'Salário'
FROM hr.employees AS E
INNER JOIN job_history AS JH
ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
WHERE MONTH(START_DATE) IN (1, 2, 3)
ORDER BY concat(FIRST_NAME, ' ', LAST_NAME), START_DATE;
