SELECT * FROM hr.countries;
SELECT * FROM hr.regions;

SELECT c.COUNTRY_ID AS "Pais Id", c.REGION_ID , r.REGION_ID AS "Região Id"
FROM countries AS c
RIGHT JOIN regions AS r
ON c.REGION_ID = r.REGION_ID
WHERE REGION_NAME = "Europe";

SELECT c.COUNTRY_NAME AS "País", IF(c.REGION_ID = 1, 'incluído', 'não incluído') AS 'Status Inclusão'
FROM countries AS c
INNER JOIN regions AS r
ON c.REGION_ID = r.REGION_ID
ORDER BY COUNTRY_NAME ASC;

SELECT * FROM hr.jobs;

SELECT JOB_TITLE AS "Cargo",
CASE
  WHEN MAX_SALARY BETWEEN 5000 AND 10000 THEN 'Baixo'
  WHEN MAX_SALARY BETWEEN 10001 AND 20000 THEN 'Médio'
  WHEN MAX_SALARY BETWEEN 20001 AND 30000 THEN 'Alto'
  WHEN MAX_SALARY > 30001 THEN 'Altíssimo'
END AS 'Nível'
FROM hr.jobs
ORDER BY JOB_TITLE ASC;

SELECT JOB_TITLE AS "Cargo", ((SELECT MAX_SALARY) - (SELECT MIN_SALARY)) AS "Diferença entre salários máximo e mínimo"
FROM hr.jobs
ORDER BY `Diferença entre salários máximo e mínimo`, JOB_TITLE ASC;

SELECT j.JOB_TITLE, AVG(e.SALARY)
FROM hr.jobs AS j
INNER JOIN employees AS e
ON j.JOB_ID = e.JOB_ID
GROUP BY JOB_TITLE;

SELECT j.JOB_TITLE AS "Cargo", AVG(e.SALARY) AS "Média salarial",
CASE
	WHEN SALARY BETWEEN 2000 AND 5800 THEN "Júnior"
	WHEN SALARY BETWEEN 5801 AND 7500 THEN "Pleno"
	WHEN SALARY BETWEEN 7501 AND 10500 THEN "Sênior"
	WHEN SALARY > 10500 THEN "CEO"
END AS 'Senioridade'
FROM hr.jobs AS j
INNER JOIN employees AS e
ON j.JOB_ID = e.JOB_ID
GROUP BY JOB_TITLE;

SELECT j.JOB_TITLE AS "Cargo", (SELECT e.SALARY,
CASE
	WHEN SALARY BETWEEN 2000 AND 5800 THEN "Júnior"
	WHEN SALARY BETWEEN 5801 AND 7500 THEN "Pleno"
	WHEN SALARY BETWEEN 7501 AND 10500 THEN "Sênior"
	WHEN SALARY > 105000 THEN "CEO"
END AS "M")
FROM hr.jobs AS j
INNER JOIN employees AS e
ON j.JOB_ID = e.JOB_ID
GROUP BY JOB_TITLE;

SELECT j.JOB_TITLE AS "Cargo", (SELECT `Media`, CASE
	WHEN SALARY BETWEEN 2000 AND 5800 THEN "Júnior"
    WHEN SALARY BETWEEN 5801 AND 7500 THEN "Pleno"
    WHEN SALARY BETWEEN 7501 AND 10500 THEN "Sênior"
    WHEN SALARY > 105000 THEN "CEO"
END AS "M") AS "Media"
FROM hr.jobs AS j
INNER JOIN hr.employees AS e
ON j.JOB_ID = e.JOB_ID;